oracle-terraform-modules/terraform-oci-oke

variables.tf

A lot of the variables do not have a default value set which they should in order to keep in-line with what the documentation specifies is required.

Bring variables.tf in-line with documentation

---

modules/oke/nodepools.tf

Image name has been hardcoded in variable file earlier. Oracle will release latest OS and instead of hardcoding the latest image name ,code has been changed to fetch the latest image id.
Signed-off-by: Karthicgit karthic.ravindran@oracle.com

Update nodepools.tf to remove the hardcoded image name

---

modules/okenetwork/security.tf

Fix for vcn_cidr to have a correct variable in okenetwork security. This is reproducible when 'allow_worker_ssh_access = true' 
Having it false it produces below error:
Error: Reference to undeclared input variable
on modules/okenetwork/security.tf line 168, in resource "oci_core_security_list" "private_workers_seclist":
168:       source    = var.vcn_cidr
An input variable with the name "vcn_cidr" has not been declared. This
variable can be declared with a variable "vcn_cidr" {} block.

fix for vcn_cidr to have correct variable name

---

docs/quickstart.adoc

Instructions for git clone was referring to old repo. Updated to point to current repository.

Instructions for git clone was referring to old repo.

---

CHANGELOG.adoc
docs/terraformoptions.adoc
docs/upgrade.adoc
locals.tf
main.tf
modules/oke/cluster.tf
modules/oke/datasources.tf
modules/oke/locals.tf
modules/oke/nodepools.tf
modules/okenetwork/locals.tf
modules/okenetwork/security.tf
modules/okenetwork/subnets.tf
modules/policies/datasources.tf
modules/policies/groups.tf
modules/policies/policies.tf
modules/policies/provider.tf
modules/policies/variables.tf
terraform.tfvars.example
variables.tf

* Missing security rule when workers are in public mode (#183)
* Updated docs for terraform options and for resetting nodepool_drain (#190)
* Upgraded base module to 1.3.0 (#191)
* Removed nat_gateway_enabled variable. Determination of whether the NAT gateway is needed is now done automatically (#192)
* Removed "LATEST" from acceptable values for kubernetes_version so that upgrade can be performed (#193)
* Internal load balancer subnet uses wrong routing table (#194)

Multiple issues: 183, 190, 191, 192, 193, 194

---

terraform.tfvars.example

Fixed incorrect K8s version in terraform.tfvars.example
Signed-off-by: Noel Dcosta <noel.dcosta@oracle.com>

Fixed incorrect K8s version in terraform.tfvars.example

---

modules/okenetwork/security.tf

OKE automatically creates new security rules for load balancers in the security list.
If you use this terraform module to upgrade the clusters OKE version, terraform deletes the new entries from the security list and breaks the load balancers.
This MR is going to address this problem.

Ignore changes made by OKE cluster to security rules.

---

modules/oke/kubeconfig.tf

Some tools don't like the *kubeconfig* file to have to wide permissions. This MR narrows those permissions so only the current user can access the file.

Narrow permissions for kubeconfig file

---

docs/terraformoptions.adoc
modules/oke/nodepools.tf
modules/oke/variables.tf
terraform.tfvars.example
variables.tf

Signed-off-by: Karthic Ravindran <karthic.ravindran@oracle.com> . PR for adding initial node labels. during cluster creation. The node_pools variable type has been changed to any from map(any) to accommodate map  .

Initial node labels addition

---

variables.tf

Removed validation as this validation will affect if new versions are released and have to update this in all releases accordingly. Validation works well  mostly for a fixed values.

removed validation for node_pool_os_version

---

modules/oke/outputs.tf
outputs.tf

Useful for other terraform resources/pipelines that would need this information.
For example Cluster autoscaler can use the nodepool ids.
Signed-off-by: Yasser Saleemi <yassersaleemi@gmail.com>

Output cluster ID and nodepool IDs

---

modules/network/locals.tf

Closes #389
The ports that are opened are from a range that are accessible only from within the worker subnet i.e. the source and destination of ingress and egress rules respectively is the worker subnet itself. This is to allow pods to communicate to each other. See the documentation here: https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengnetworkconfig.htm#securitylistconfig

docs: 'updated description for 1 rule'

---

modules/oke/nodepools.tf

Do not enforce consumers to create a node pool with a single worker in it, just create an empty node pool and let people decide what do to with that.
Closes: https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/400

Fix node pool size definition

---

modules/extensions/kubeconfig.tf
modules/extensions/scripts/kubeconfig_set_credentials.template.sh
modules/extensions/scripts/token_helper.template.sh

Closes #429. Removed hard-coded region and cluster id parameters so the operator can be used to
manage more than 1 OKE cluster. The presence of the token improves the performance of issuing 
kubectl commands to clusters in different regions considerably.

feat: enhancements to token_helper for kubectl. Closes #429

---

main.tf

Updated the Operator version to v3.0.1 from v3.0.0. v3.0.1 has OSMS disabled feature

updated the operator version to 3.0.1 from 3.0.0

---

examples/verrazzano/verrazzano.tf
modules/extensions/activeworker.tf
modules/extensions/calico.tf
modules/extensions/drain.tf
modules/extensions/gatekeeper.tf
modules/extensions/iam.tf
modules/extensions/k8stools.tf
modules/extensions/kubeconfig.tf
modules/extensions/metricserver.tf
modules/extensions/secrets.tf
modules/extensions/serviceaccount.tf

Closes #447 
Terraform file provisioner accept only absolute path . Changed path ~ to /home/opc  in all provisioner file in extensions module since its not working in terraform latest version .

fix: File provisioner path ~ changed to /home/opc

---

docs/configuration.adoc
docs/instructions.adoc
docs/terraformoptions.adoc
main.tf
modules/oke/iam.tf
modules/oke/locals.tf
modules/oke/variables.tf
terraform.tfvars.example
variables.tf

Fixed empty policy bug by adding new use_node_pool_volume_encryption variable
added oke-tags to freeform_tags in terraform.tfvars.example
Signed-off-by: Nikhil Kota <srinivasa.nikhil.kota@oracle.com>

fix: fixed empty policy issue and added oke-tags to freeform_tags in terraform.tfvars.example

---

main.tf

when a custom image is used. Closes #516

fix: autonomous cloud-init template should not be used 

---

docs/configuration.adoc
docs/instructions.adoc
docs/terraformoptions.adoc
main.tf
modules/extensions/iam.tf
modules/extensions/variables.tf
modules/oke/iam.tf
modules/oke/locals.tf
modules/oke/outputs.tf
modules/oke/variables.tf
terraform.tfvars.example
variables.tf

- revived create_policies variable
- if create_policies is false - no OIM changes will be done. Neither dynamic group nor policies/
- This is very useful when OIM is managed by another team and you don't have rights to change or query it.

create_policies variable to turn off any potential policy creation tempt (#325)

---

main.tf

so it doesn't trigger a deletion and recreation of resources if out-of-band modifications are done to it. Closes #417

fix: added lifecycle meta-argument on default security list 

---

docs/terraformoptions.adoc
modules/oke/locals.tf
modules/oke/nodepools.tf
terraform.tfvars.example

I haven't been able to test it yet, as I'm still working on getting a test environment up, but in the meantime the maintainers can tell if there are issues with the documentation or the commit message.
----
The `node_pools` argument gained a new optional key `placement_ADs`.
This key can be popolated by a list, like:
`placement_ADs = ["sQTi:EU-FRANKFURT-1-AD-1"]`
to choose the ADs the pool will deploy nodes to.
Default remains to deploy to all ADs of region.
Fixes: #515
Signed-off-by: Andrea Stacchiotti <andreastacchiotti@gmail.com>

Added option to specify ADs in node pools

---

modules/network/nsgs.tf

The current rule has both tcp and icmp options.
Signed-off-by: Omar Aloraini <ooraini.dev@gmail.com>

fix icmp in cp_ingress_additional_cidrs nsg rule

---

datasource.tf
docs/instructions.adoc
docs/terraformoptions.adoc
locals.tf
main.tf
modules/extensions/activeworker.tf
modules/extensions/calico.tf
modules/extensions/drain.tf
modules/extensions/gatekeeper.tf
modules/extensions/iam.tf
modules/extensions/k8stools.tf
modules/extensions/kubeconfig.tf
modules/extensions/locals.tf
modules/extensions/metricserver.tf
modules/extensions/secrets.tf
modules/extensions/serviceaccount.tf
modules/extensions/variables.tf
modules/network/nsgs.tf
modules/oke/cluster.tf
modules/oke/datasources.tf
modules/oke/nodepools.tf
modules/storage/datasource.tf
outputs.tf
terraform.tfvars.example
variables.tf

- Ignore lifecycle changes for automatic tagging and dynamic variables/templates
- Support variable names populated by [Resource Manager](https://docs.oracle.com/en-us/iaas/Content/ResourceManager/Concepts/terraformconfigresourcemanager.htm#configvar)
- Use specific compartment for AD listing in case different
- Use stable random suffix for dynamic group name (resolves #556)
- Fall back to provided bastion/operator addresses, SSH user (resolves #555)
Some lifecycle changes are reported from other modules:
https://github.com/oracle-terraform-modules/terraform-oci-operator/pull/68
https://github.com/oracle-terraform-modules/terraform-oci-operator/pull/69
https://github.com/oracle-terraform-modules/terraform-oci-bastion/pull/50
Repeated apply:
```
~ resource "oci_core_service_gateway" …
```

fix: Ignore lifecycle changes, support Resource Manager variables

---

docs/terraformoptions.adoc
locals.tf
main.tf
modules/extensions/locals.tf
provider.tf.example
variables.tf

* Update modules: vcn 3.5.2, bastion 3.1.3, operator 3.1.2
* Support base64-encoded SSH, API keys
* Add `provider.tf.example` for convenience

Update modules, support base64-encoded SSH key

---

docs/quickstart.adoc
locals.tf

```
│ Error: Error in function call
│
│   on .terraform/modules/admin/locals.tf line 10, in locals:
│   10:   user_id = coalesce(var.user_id, var.current_user_ocid)
│     ├────────────────
│     │ var.current_user_ocid is ""
│     │ var.user_id is ""
```
Links to https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/provider.tf.example

fix: Provide empty fallback value for user_id local

---

modules/network/subnets.tf

use - instead of combinations of - and _ and change the dns labels to ilb for internal load balancer and plb for public load balancer. 
Inspired by @ooraini's contrib

chore: cosmetic changes to load balancer subnet names and labels

---

CHANGELOG.adoc
docs/instructions.adoc
main.tf
modules/extensions/kubeconfig.tf
modules/extensions/variables.tf
variables.tf

Fixes #601 
This PR removes the creation of a local kubeconfig file and adds instructions so, users select how it wants to manage the kubeconfig information data.
Also removes the `update_kubeconfig` flag as isn't required anymore.
Note: I don't know where to add the changelog changes for unreleased ones.

feat: Remove local kubeconfig file creation and `update_kubeconfig` input var

---

CHANGELOG.adoc
docs/configuration.adoc
docs/quickstart.adoc
docs/terraformoptions.adoc
main.tf
modules/extensions/scripts/install_gatekeeper.template.sh
modules/extensions/templates.tf
modules/extensions/variables.tf
modules/network/subnets.tf
modules/network/variables.tf
modules/storage/subnet.tf
modules/storage/variables.tf
terraform.tfvars.example
variables.tf

1. Add a new `assign_dns` boolean variable with default of `true` to match current behavior. When `false`, the optional `dns_label` values for OKE subnets will be unset, resulting in disabled DNS resolution of hostnames within the subnet. This also provides one option to avoid issues with `label_prefix` when the DNS names are unused; other changes for added flexibility will be considered separately.
References:
* [core_vcn#dns_label](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_vcn#dns_label)
* [oci_core_subnet#dns_label](https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/core_subnet#dns_label)
```
assign_dns = false
```
> DNS Domain Name: DNS isn’t enabled for this VCN
> DNS Domain Name: DNS isn’t enabled for this Subnet
2. Don't …

feat: Support disabled DNS record assignment for OKE subnets

---

modules/network/locals.tf

Resolves https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/608
As per the Oracle Kubernetes Engine [documentation](https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengnetworkconfig.htm) the Kubernetes API endpoint on ports `TCP/6443` and `TCP/12250` allows ingress traffic to the Control Plane subnet.
Signed-off-by: James Marino <james@marino.io>

fix: added kubernetes api control plane network access for pods

---

modules/extensions/k8stools.tf

These utilities are now installed earlier in cloud-init, however a race still exists between setup that uses them in the `extensions` module. This change blocks the k8stools operator installation step until cloud-init has completed.
Resolves #610

Wait for cloud-init completion before k8s extension install

---

CHANGELOG.adoc
main.tf

Update `terraform-oci-operator` module  version to support passing existing `assign_dns` var, so that operator subnet and instance are correctly provisioned when VCN DNS resolution is disabled.

fix: Operator support for disabled VCN DNS

---

CHANGELOG.adoc
main.tf
modules/storage/fss.tf
versions.tf

* Update terraform-oci-bastion module version to support passing existing `assign_dns` var, so that bastion subnet and instance are correctly provisioned when VCN DNS resolution is disabled.
* Perform the same assign_dns check for FSS hostname_label (subnet already covered)
* Update minimum Terraform version to 1.1 (Resolves #616)

fix: Bastion & FSS support for disabled VCN DNS, min TF version -> 1.1

---

modules/oke/outputs.tf
outputs.tf

Small change to output endpoints... justification:
Deploying the stack via Oracle Resource Manager/Market Place.  Terraform calls an Ansible playbook as part of the deployment for config mgmt of the cluster and requires access to the control plane (no operator is deployed).  
Access to the CP can be made through Resource Manager Private Endpoints, but to do so, the private endpoint IP must be known, for example:
```
data "oci_resourcemanager_private_endpoint_reachable_ip" "orm_pe_reachable_ip" {
count               = var.orm_install ? 1 : 0
private_endpoint_id = oci_resourcemanager_private_endpoint.orm_pe[0].id
private_ip          = split(":", module.oke.cluster_endpoints[0].private_endpoint)[0]
}
```
This will provide an IP (`data.oci_resourcemanager_private_endpoint_reachable_ip.orm_pe_r …

Output Endpoints

---

modules/oke/nodepools.tf

Correct terraform syntax to ignore just the needed parts of `node_metadata` and `node_config_details`
Before the change the whole sub-objects were ignored, leading to inability to change a nodepool size via terraform.
Fixes: 269d3fdd89

Node pool correctly ignore sub-sub-object

---

main.tf

The Internet Gateway is not created if the Load Balancer subnet is PRIVATE and Control Plane is PUBLIC. This PR is fixing this issue

fix: Correct Internet Gateway creation rule

---

modules/oke/cluster.tf

In case if user provision OKE with internal LB and doesn't set perferred_load_balancer variable the terraform will fail during provision with unintuitive message:
> Error: 400-InvalidParameter, Invalid subnetId: subnetId must not be blank
> │ Suggestion: Please update the parameter(s) in the Terraform config as per error message Invalid subnetId: subnetId must not be blank
> │ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster 
> │ API Reference: https://docs.oracle.com/iaas/api/#/en/containerengine/20180222/Cluster/CreateCluster 
> │ Request Target: POST https://containerengine.us-ashburn-1.oci.oraclecloud.com/20180222/clusters 
> │ Provider version: 4.102.0, released on 2022-12-14. This provider is 2 Update(s) behind to …

fix: add preferred_loadbalancer validation

---

modules/extensions/resources/calico/calico-node-env-flannel.yaml

See https://github.com/projectcalico/calico/issues/6546#issuecomment-1313496096 - the "policy only" manifest overrides the default value for this environment variable to `false`.

fix: Set CALICO_MANAGE_CNI for Calico w/ Flannel

---

docs/terraformoptions.adoc
locals.tf
main.tf
modules/workerpools/README.md
modules/workerpools/clusternetworks.tf
modules/workerpools/datasources.tf
modules/workerpools/instanceconfig.tf
modules/workerpools/instancepools.tf
modules/workerpools/locals.tf
modules/workerpools/nodepools.tf
terraform.tfvars.example
variables-workerpools.tf
variables.tf
vars-workerpool.auto.tfvars.example
workerpools.tf

- Add experimental configuration for secondary VNICs
- Use correct defaults by mode for block volume config
- Use Kubernetes v1.25 by default
- Use consistent worker image lookup and variables
- Add precondition for better error message with missing image_id
- Fix worker pool resource display names with removed label_prefix

Secondary VNIC for IP/CN, compatible defaults for block volume/AD

---

main.tf
modules/oke/nodepools.tf
modules/oke/variables.tf
variables.tf

https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/628
An OKE nodepool is limited to 32 chars.
var.label_prefix can sometimes consume most of those chars, leaving little room for the remainder of the node pool name as defined in each key name of var.node_pools.
for a more descriptive nodepool name we should have the ability to drop the var.label_prefix name specifically for the oci_containerengine_node_pool resource. this way, we can maintain the functionality of var.label_prefix that is used across this terraform module.
to validate this change:
```
module "oke" {
source = "oracle-terraform-modules/oke/oci"
ignore_label_prefix_in_node_pool_names = true  
....
}
```

feat: Optionally ignore the label prefix in node pool names

---

docs/clusterautoscaler.adoc
locals.tf
main.tf
modules/extensions/autoscaler.tf
modules/extensions/resources/clusterautoscaler.template.yaml
modules/extensions/scripts/create_autoscaler_pool_taint_list.py
modules/extensions/scripts/taint_autoscaler_pool.template.sh
modules/extensions/templates.tf
modules/extensions/variables.tf
modules/network/subnets.tf
modules/oke/autoscaler.tf
modules/oke/datasources.tf
modules/oke/locals.tf
modules/oke/outputs.tf
modules/oke/variables.tf
outputs.tf
terraform.tfvars.example
variables.tf

Resolves #273
This PR adds a separate unmanaged node pool for the purpose of deploying the cluster autoscaler. The node pool has the following characteristics:
- deployed separately from other nodepools
- defined tags (oke.pool = ~~"syspool"~~ "autoscaler") applied to nodepool and its nodes so that the nodes will be part of autoscaler dynamic group
- fixed shape to Flex E4, 2 OCPUs and 32 GB memory
- fixed size of 3 worker nodes so we can deploy 3 replicas
- fixed labels (app="cluster-autoscaler"). ~~Autoscaler will need to implement this as nodeSelector.~~
- taints (autoscaler=true:NoSchedule). ~~Autoscaler deployment will need to implement this as tolerations.~~ This will help restrict other deployments from this node. Need to change the taint and update the toleration.
- should work …

feat: adds a separate nodepool to run cluster autoscaling

---

modules/workers/instanceconfig.tf

Availability domain is specified on the pool and not required at this level.

fix: Use correct block volume specification for multi-AD instance config

---

modules/workers/instanceconfig.tf
modules/workers/nodepools.tf
variables-workers.tf

- Leave user data variable unset when not provided an explicit value - determined automatically.

fix: Only add cluster DNS when provided, or determined automatically

---

modules/workers/clusternetworks.tf

Ignored lifecycle for block keys had the block ignored, including `size`.

fix: Honor changes to pool size for CN

---

module-bastion.tf
variables-bastion.tf

- Use Oracle Autonomous Linux by default for bastion host

fix: Update bastion image selection

---

modules/bastion/cloudinit.tf
modules/operator/cloudinit.tf

- Re-trigger null resource to await completion of cloud-init when operator/bastion hosts are replaced.

fix: Re-trigger await cloud-init on bastion/operator replacement

---

module-cluster.tf

- Disable public kube_config source with private endpoint

fix: No public kube_config datasource for private endpoint

---

modules/workers/instanceconfig.tf

- Use fixed AD selection for `cluster-network` mode when multi-AD

fix: Update AD selection for instance config mode

---

modules/iam/group-autoscaling.tf

- Add `compute-management-family` policy used by `oci` cloud provider

fix: Add compute-management-family to cluster autoscaler policy

---

modules/workers/locals.tf

- Add k8s node labels with Terraform state information:
```json
{
"oke.oraclecloud.com/tf.module": "terraform-oci-oke"
"oke.oraclecloud.com/tf.state_id": "<state ID>"
"oke.oraclecloud.com/tf.workspace": "<TF workspace>"
"oke.oraclecloud.com/pool.name": "<pool name>"
"oke.oraclecloud.com/pool.mode": "<pool mode>"
},
```

feat: Add TF node labels

---

module-workers.tf
modules/workers/instanceconfig.tf
modules/workers/nodepools.tf
modules/workers/variables.tf
variables-workers.tf

Adds a `worker_node_metadata` map variable for extra user-defined entries, merged with existing.

feat: Support custom worker instance metadata

---

module-network.tf

Minor fix to include the required `create_cluster` variable to the network sub-module.

fix: Provide var.create_cluster to network module

---

modules/workers/clusternetworks.tf
modules/workers/instanceconfig.tf

Minor updates to lifecycle ignore rules for tags based on further testing.

fix: Ignore tags for instance config VNIC details, CN instance pools

---

module-network.tf
variables-network.tf

This change maintains the current behavior by default, with new variables that allow VCN gateway creation to be disabled or forced - e.g. in cases where custom resources ([core_route_table](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_route_table), [core_route_table_attachment](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_route_table_attachment), etc.) are provisioned outside of the module.
```
vcn_create_nat_gateway      = "never"  # never/auto*/always
vcn_create_internet_gateway = "auto"   # never/auto*/always
vcn_create_service_gateway  = "always" # never/auto/always*
```

feat: Add configuration for VCN gateway creation

---

modules/network/subnets.tf

Bug fix for evaluation of the `subnets` map - checking existence of key doesn't cover key present with null value.

fix: 5.x Evaluate subnets definition with omitted fields correctly

---

data-common.tf
module-bastion.tf
module-cluster.tf
module-extensions.tf
module-iam.tf
module-network.tf
module-operator.tf
module-workers.tf

Use only lowercase alpha characters for generated `state_id` variable, to keep it compatible with some resource name constraints.

fix: Resource name-safe state_id

---

examples/vars-cluster.auto.tfvars
module-cluster.tf
modules/cluster/variables.tf
variables-cluster.tf
versions.tf

- Add [oci_containerengine_cluster#type](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster#type) for [Enhanced clusters](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengworkingwithenhancedclusters.htm)
- Update `oci` provider version to `~> 4.114.0`

feat: 5.x Add oci_containerengine_cluster type variable

---

module-workers.tf
modules/workers/locals.tf
modules/workers/nodepools.tf
modules/workers/variables.tf
variables-workers.tf
versions.tf

This enables preemptible worker nodes during nodepool creation.
Examples of some of the invocations:
Default worker_preemptible:
`worker_preemptible_config = {enable = "false", is_preserve_boot_volume = "false"}`
Enable Preemptible :
`preemptible_np = { mode = "node-pool", size = 1, create = true, allow_autoscaler = true, placement_ads = [1] , preemptible_config = {enable = true, is_preserve_boot_volume = true}},`
Enable Preemptible with out preserving boot volume:
`preemptible_np1 = { mode = "node-pool", size = 1, create = true, allow_autoscaler = true, placement_ads = [2], 
preemptible_config = {enable = true, is_preserve_boot_volume = false}},`
Do not use Preemptible np:
`ondemand_np = { mode = "node-pool", size = 1, create = true, allow_autoscaler = true, placement_ads = [2]},` …

Preemptible 5.x

---

modules/workers/instanceconfig.tf

Makes expected VNIC attachment information available to worker nodes through instance metadata when available.

feat: 5.x Add configured VNICs to instance metadata when available

---

docs/codingconventions.adoc
module-cluster.tf
module-network.tf
module-workers.tf
modules/cluster/cluster.tf
modules/workers/instance.tf
modules/workers/locals.tf
modules/workers/nodepools.tf
modules/workers/outputs.tf
variables-network.tf
variables-workers.tf

- Fix for over-matching with node pool lifecycle ignore.
- Add `mode = "instance"` for individual self-managed nodes outside of a pool. Extended fields pending implementation aren't required with standard usage and left for context later. Provides a simple reference implementation for the `oci_core_instance` resource and can be helpful with certain testing.

fix: 5.x Lifecycle ignore fixes, individual worker mode

---

modules/oke/nodepools.tf

The OCI prvider (4.114.0) wants a value of 0 timeout to be formatted as PT0S instead of PT0M, and would give plan residuals against PT0M, even though they are clearly equivalent.
So special case 0 minutes to be formatted as PT0S. No functional change.
Fixes: #688

Correct eviction grace duration in case of 0 (or default) timeout

---

modules/oke/nodepools.tf
terraform.tfvars.example
versions.tf

Add support for preemptible worker nodes
Terraform plan differences from following configuration:
```hcl
node_pools = {
np1 = {
shape            = "VM.Standard.1.1",
ocpus            = 1,
memory           = 1,
node_pool_size   = 1,
boot_volume_size = 150,
eviction_grace_duration = 0,  //Grade duration in minutes. Service default is 60.
force_node_delete       = true
}
preemptible = {
shape            = "VM.Standard.1.1",
ocpus            = 1,
memory           = 1,
node_pool_size   = 1,
boot_volume_size = 150,
eviction_grace_duration = 0,  //Grade duration in minutes. Service default is 60.
force_node_delete       = true
preemptible_config = {"enable": true, "is_preserve_boot_volume": true}
}
preemptible1 = {
shape            = "VM.Standard.1.1",
ocpus            = 1,
memory           = 1, …
```

feat: [4.x] Add support for preemptible worker nodes

---

modules/workers/cloudinit-oke.sh

Value of `--kubelet-ca-cert` is already decoded within `oke-install.sh`.

fix: Remove redundant decode for OKE init parameter

---

docs/terraformoptions.adoc
variables.tf

Not tagging should be the default behaviour, consistently with defined_tags, to not force the user to override with an empty map.
Also clean up defaults and documentation.

Make the default freeform_tags empty

---

module-network.tf
modules/network/nsg-bastion.tf
modules/network/nsg-controlplane.tf
modules/network/variables.tf
variables-cluster.tf
variables-network.tf

Added `allow_bastion_cluster_access` variable defaults to `false` to match existing behavior. When `true`, the bastion host NSG is allowed access to the k8s apiserver endpoint.
No changes to existing state when `false`.
Plan when updated to `true`:
```
+ resource "oci_core_network_security_group_security_rule" "oke" {
+ description               = "Allow TCP egress from bastion to cluster endpoint"
+ destination               = "ocid1.networksecuritygroup..."
+ destination_type          = "NETWORK_SECURITY_GROUP"
+ direction                 = "EGRESS"
+ id                        = (known after apply)
+ is_valid                  = (known after apply)
+ network_security_group_id = "ocid1.networksecuritygroup..."
+ protocol                  = "6"
+ source_type               = (known after …
```

feat: Add optional NSG rule for bastion k8s endpoint access

---

versions.tf

The oke module is a reusable module, hence it must not force the whole root module to un under a certain minor release of the oci provider.
Fixes: 830192e3e59c716f

Use lower bound version specification for oci provider

---

module-workers.tf
modules/workers/cloudinit.tf
modules/workers/locals.tf
modules/workers/variables.tf
variables-workers.tf

Added a variable named `disable_default_cloud_init` so users can prevent the default OKE cloud-init from being merged to the user-provided cloud-init if desired. If `disable_default_cloud_init` is set to true, the worker pools will be created using only the cloud-init explicitly provided in `worker_cloud_init`. If `disable_default_cloud_init` is set to false (default), the workers module will continue using the existing behavior of merging a default OKE cloud-init with the cloud-init provided by the user.
Sample plan with `disable_default_cloud_init` set to true:
```
+ resource "oci_core_instance_configuration" "workers" {
+ compartment_id  = "ocid1.compartment.oc1..aaaaaaaacurnu3oxtnm42pdgsj4gnmtn4qjdf47k74g7e7lz54uov5k5mq5q"
+ deferred_fields = (known after apply)
+ defined_tags    = { …
```

feat: Add ability to override default cloud-init set by OKE in worker pools

---

modules/workers/locals.tf

- Fix incorrect `node_labels` reference to use pool-level configuration when present.

fix: 5.x Use pool-level node_labels

---

modules/workers/locals.tf

* Include `mode: instance` pools in detailed `worker_pools` output.
* Each pool with `mode: instance` should be numbered independently rather than in a group as before.
Before:
```
poolA-0
poolA-1
poolA-2
poolB-3
poolB-4
poolB-5
```
After:
```
poolA-0
poolA-1
poolA-2
poolB-0
poolB-1
poolB-2
```

fix: 5.x Use correct suffix numbering for pools with mode=instance

---

versions.tf

Fix in main (4.x): https://github.com/oracle-terraform-modules/terraform-oci-oke/commit/eedebc047a4747ba89a443830ed7be80fa9f90e0 and other.

fix: 5.x Relax TF provider version constraints

---

examples/vars-bastion.auto.tfvars
module-bastion.tf
module-cluster.tf
module-network.tf
module-operator.tf
module-workers.tf
modules/network/nsg-bastion.tf
modules/network/nsg-controlplane.tf
modules/network/nsg-fss.tf
modules/network/nsg-loadbalancers-int.tf
modules/network/nsg-loadbalancers-pub.tf
modules/network/nsg-operator.tf
modules/network/nsg-pods.tf
modules/network/nsg-workers.tf
modules/network/rules.tf
modules/network/subnets.tf
modules/network/variables.tf
modules/workers/instance.tf
modules/workers/instancepools.tf
modules/workers/nodepools.tf
variables-bastion.tf
variables-cluster.tf
variables-network.tf
variables-workers.tf
versions.tf

* Add preconditions for better error messaging with image/NSGs configuration issues.
* Support `create_vcn = false` and undefined `vcn_id` for workers with an existing cluster and subnets, where VCN information is not needed.
* Provide `pod_subnet_ids` as list when `var.cni_type == "npn"` - resolves #682.
Example - worker pool with existing subnet and cluster:
```
cluster_id         = "ocid1.cluster..."
create_cluster     = false
create_bastion     = false
create_nsgs        = false
create_vcn         = false
create_operator    = false
create_nsgs_always = false
worker_pools = {
np1 = { size = 1 },
}
subnets = {
workers = { id = "ocid1.subnet..." }
}
```
Before:
```
│ Error: Missing required argument
│ 
│   with data.oci_core_vcn.oke[0],
│   on module-network.tf line 6, in data …
```

fix: 5.x TF 1.3, subnet/NSG objects, NSG/image preconditions, unrequired VCN

---

modules/workers/instanceconfig.tf

`extended_metadata` on the oci_core_instance_configuration resource is specified under `instance_details[0].launch_details[0].extended_metadata`.

fix: 5.x Specify lifecycle ignore for extended_metadata at correct level

---

modules/workers/data-shapes.tf
modules/workers/instance.tf
modules/workers/instanceconfig.tf

* Resolve errors caused by multiple results for a given shape, e.g. in multi-AD regions. The fields that might differ between these aren't used for our purpose.
* Remove previously added lifecycle ignore for `extended_metadata` in favor of `{}` default or optional pool configuration, to mitigate cosmetic differences reported on subsequent apply.
```
Error: Duplicate object key
│
│   on .terraform/modules/oci_workers/modules/workers/data-shapes.tf line 11, in locals:
│    9:   shapes_by_name = {
│   10:     for shape in data.oci_core_shapes.oke.shapes :
│   11:     lookup(shape, "name") => shape if contains(keys(shape), "name")
│   12:   }
│
│ Two different items produced the key "VM.Standard.x86.Generic" in this 'for' expression. If duplicates are expected, use the ellipsis
│ (...) after …
```

fix: 5.x Merge redundant shape results for `platform_config` `type` lookup

---

modules/workers/locals.tf

Add default value for `extended_metadata` used by pools.

fix: Include empty default for pool extended_metadata

---

data-images.tf
examples/oke-workers/main.tf
module-bastion.tf
module-cluster.tf
module-network.tf
module-operator.tf
module-workers.tf
modules/iam/group-autoscaling.tf
modules/iam/group-cluster.tf
modules/iam/group-operator.tf
modules/iam/group-workers.tf
modules/iam/policy.tf
modules/network/drgs.tf
modules/network/subnets.tf
modules/workers/instance.tf
modules/workers/instanceconfig.tf
modules/workers/locals.tf

* Add error handling for missing `subnet_id` values, e.g. when unused or with `terraform destroy`. Inputs are better validated by the resources that use them and their preconditions.
* Improve null handling with string interpolation. The `%v` format verb yields "null" in a string instead of an error - e.g. when unused/destroying.
Example failure for missing subnet/NSG with `terraform destroy`:
```
module.oke.module.workers[0].oci_core_instance_pool.workers["wp1"]: Refreshing state... [id=...]
╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/oke/module-workers.tf line 62, in module "workers":
│   62:   pod_subnet_id              = module.network.pod_subnet_id
│     ├────────────────
│     │ module.network is object with 17 attributes
│
│ This object does not have an attribute …
```

fix: 5.x Safe handling of null values in strings on missing/destroy

---

outputs.tf

This commit Updates the terraform output for `ssh_to_operator` so that you can use a private key that is anywhere on the filesystem.  Currently the short form (`-J`) does not allow you to pass any arguments like `-i`, therefore if your ssh key is not in a default location that openssh knows about it will fail to connect.
More info in this issue: https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/246

Fix: ssh_to_operator output use long form

---

module-bastion.tf
module-cluster.tf
module-iam.tf
module-network.tf
module-operator.tf
module-workers.tf
modules/bastion/compute.tf
modules/cluster/cluster.tf
modules/cluster/variables.tf
modules/iam/tagging.tf
modules/network/drgs.tf
modules/network/locals.tf
modules/network/nsg-bastion.tf
modules/network/nsg-controlplane.tf
modules/network/nsg-fss.tf
modules/network/nsg-loadbalancers-int.tf
modules/network/nsg-loadbalancers-pub.tf
modules/network/nsg-operator.tf
modules/network/nsg-pods.tf
modules/network/nsg-workers.tf
modules/network/subnets.tf
modules/operator/compute.tf
modules/workers/locals.tf
variables-iam.tf

* Add resource tagging consistently, fix issues merging inputs.
* Merge common tag attributes outside of submodules to materialize earlier, i.e. visible in plan vs. "(known after apply)".
* Workers may still be known after apply due to merge with pool-level configuration, but should have tags applied correctly after.

fix: 5.x Add missing resources tags, materialize early

---

module-workers.tf
modules/workers/instance.tf
modules/workers/instanceconfig.tf
modules/workers/locals.tf
modules/workers/nodepools.tf
modules/workers/variables.tf
variables-workers.tf

Resolves https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/740 to add support for capacity reservation for worker nodes
Sample usage for different types of worker pools:
```
worker_pools = {
np_enhanced = {
mode = "node-pool", size = 1,
capacity_reservation_id = "ocid1.capacityreservation...",
placement_ads = [1]
},
ip_enhanced = {
mode = "instance-pool", size = 1,
capacity_reservation_id = "ocid1.capacityreservation..."
},
instance_enhanced = {
mode = "instance", size = 1,
capacity_reservation_id = "ocid1.capacityreservation..."
}
}
```
Note: setting a capacity reservation for a node-pool is only allowed if a single AD is specified for the node-pool. You may have to set placement_ads = [<AD number>] when using capacity reservation with standalone instances or instance …

adding capacity reservation support for workers

---

modules/iam/group-workers.tf

* Flatten and `tolist()` for local IAM policy statement variable
Resolves #746

fix: 5.x Flatten and tolist policy statements

---

migration.tf

* Add 4.x->5.x migration blocks for subnets, cluster
These are not yet comprehensive for breaking changes between major versions, but address some resource moves.
Closes #733

feat: Add 4.x->5.x migration blocks for subnets, cluster

---

module-bastion.tf

Home provider is no longer used and should not be passed into submodule:
```
│ Error: Reference to undefined provider
│ 
│   on .terraform/modules/cluster/module-bastion.tf line 60, in module "bastion":
│   60:     oci.home = oci.home
│ 
│ The child module does not declare any provider requirement with the local name "oci.home".
│ 
│ If you also control the child module, you can add a required_providers entry named "oci.home" with the source address "oracle/oci" to accept this provider
│ configuration.
╵
```

fix: 5.x Remove unrequired home provider for bastion submodule

---

data-images.tf
module-bastion.tf
module-operator.tf
modules/extensions/versions.tf
modules/network/nsg-bastion.tf
modules/network/nsg-controlplane.tf
modules/network/nsg-fss.tf
modules/network/nsg-loadbalancers-int.tf
modules/network/nsg-loadbalancers-pub.tf
modules/network/nsg-operator.tf
modules/network/nsg-pods.tf
modules/network/nsg-workers.tf

- Disable bastion/operator/worker image datasources when unused, handle empty result
- Fix evaluation of `create = auto` (default) for NSGs
- Relax version constraints for extensions submodule
Resolves #745

fix: 5.x Disable unused datasources, create NSGs with auto defaults

---

examples/workers/vars-workers-advanced.auto.tfvars
examples/workers/vars-workers-autoscaling.auto.tfvars
examples/workers/vars-workers-basic.auto.tfvars
examples/workers/vars-workers-clusternetwork.auto.tfvars
examples/workers/vars-workers-drain.auto.tfvars
examples/workers/vars-workers-instance.auto.tfvars
examples/workers/vars-workers-instancepool.auto.tfvars
examples/workers/vars-workers-network-vnics.auto.tfvars
examples/workers/vars-workers-nodepool.auto.tfvars

Instead of putting multiple variables on one line, put variables on separate lines.
These examples get rendered into documentation,
so this makes these files more readable.

docs: improve formatting of examples/workers tfvars

---

examples/network/vars-network-subnets-create-force.auto.tfvars
examples/profiles/network-only/main.tf
examples/rms/oke-network-only/main.tf

I personally find things a bit easier to understand in the examples
when the variables are specified on multiple lines.

docs: improve formatting by putting more variables different lines

---

module-bastion.tf
module-cluster.tf
module-network.tf
module-operator.tf

Change `var.state_id` -> `local.state_id` in resource tags for proper [fallback to generated value](https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/data-common.tf#L5) when `use_defined_tags = true`.

fix: 5.x Use correct state_id var in resource tags

---

docs/src/guide/workers_drain.md
examples/profiles/workers-only/main.tf
examples/profiles/workers-only/variables.tf
examples/workers/vars-workers-drain.auto.tfvars
module-utilities.tf
module-workers.tf
modules/utilities/drain.tf
modules/utilities/variables.tf
modules/utilities/versions.tf
modules/workers/locals.tf
modules/workers/outputs.tf
variables-utilities.tf

Implement draining of pools by label through the operator instance with `drain = true` on a `worker_pools` entry. Review added documentation/examples for more detail.
Closes #751

feat: 5.x Implement worker pool drain

---

modules/workers/instance.tf
modules/workers/instanceconfig.tf
modules/workers/instancepools.tf
modules/workers/locals.tf
modules/workers/nodepools.tf
modules/workers/virtualnodepools.tf

* Omit placement fault domains unless specified to avoid changes to existing resources, as input is not required when mode != `virtual-node-pool`.

fix: 5.x Unspecified default placement FDs when mode != virtual-node-pool

---

docs/src/guide/operator_identity.md

Added some clarifying text on operator instance principal, based on
discussion in https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/776

docs: Add clarifying examples for operator instance principal

---

examples/workers/vars-workers-drain.auto.tfvars
module-workers.tf
modules/workers/locals.tf
modules/workers/nodepools.tf
modules/workers/outputs.tf

* Updated worker outputs for instance IDs => IPs where available
```
Outputs:
worker_pool_ips = {
"example-mode-instance" = {
"ocid1.instance..." = "10.x.x.x"
}
"example-mode-nodepool" = {
"ocid1.instance..." = "10.x.x.x"
}
}
```
* Managed node pool cordon & drain eviction grace period in seconds; fixes reported change:
```
~ resource "oci_containerengine_node_pool" "workers" {                                                                                                                                
...
~ node_eviction_node_pool_settings {
~ eviction_grace_duration              = "PT0S" -> "PT0M"
}
```

feat: 5.x Update outputs for worker pools/ips/ids, eviction grace in seconds

---

modules/network/subnets.tf

If `prohibit_public_ip_on_vnic` isn't ignored, then changing the k8s API endpoint between public and private requires recreating the entire cluster.

Fix: Ignore prohibit_public_ip_on_vnic changes in control plane subnet

---

module-bastion.tf
module-operator.tf
modules/bastion/compute.tf
modules/network/subnets.tf
modules/operator/compute.tf
modules/workers/locals.tf
variables-common.tf
variables-network.tf

- Fix evaluation of `dns_label` in `var.subnets` to use specified/generated values when `var.assign_dns = true` (Fixes #780)
- Consistent lifecycle ignore of `dns_label` with bastion/operator `hostname_label`
- Add error handling for `cloud_init.content` when attempting evaluation as file path
- Cosmetic fixes and safe interpolation for bastion/operator SSH commands (Fixes #782)

fix: 5.x Subnet dns_label, cloud_init error handling, SSH command cleanup

---

docs/src/guide/extensions_cluster_autoscaler.md
examples/workers/vars-workers-autoscaling.auto.tfvars
modules/extensions/autoscaler.tf

- Update Cluster Autoscaler docs/examples with correct `min_size`/`max_size` parameters
- Update Cluster Autoscaler deployment image tag version -> `1.26.2-7` ([reference](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm))

fix: 5.x Update Cluster Autoscaler docs, image tag

---

module-operator.tf
modules/network/nsg-bastion.tf
modules/network/nsg-controlplane.tf
modules/network/nsg-fss.tf
modules/network/nsg-loadbalancers-int.tf
modules/network/nsg-loadbalancers-pub.tf
modules/network/nsg-operator.tf
modules/network/nsg-pods.tf
modules/network/nsg-workers.tf

The fallback to "auto" was not working properly as a value of `null` was found:
```
lookup(local.bastion_nsg_config, "create", "auto") == "always",
```
This is now coalesced to the default value "auto" as expected.

fix: 5.x Evaluation for auto NSG creation with defaults

---

README.md

See rendered version of this README: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/ba1a892fbb8fc6b9e2d0fa390dc394f5ea466f91/README.md
Partially addresses #810
@robo-cap

docs: Push link to documentation further up in README

---

modules/workers/locals.tf

fix: #808 and inconsistency introduced in PR https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/814
cc. @devoncrouse and @robo-cap 
and RC-5 contains the issue: https://github.com/oracle-terraform-modules/terraform-oci-oke/releases/tag/v5.0.0-RC5

5.x:  fix tag_namespace delimiter is a dot.

---

data-images.tf
docs/src/SUMMARY.md
docs/src/guide/rms_nodepool.md
docs/src/guide/upgrade.md
docs/src/guide/workers_node_cycle.md
modules/workers/locals.tf
modules/workers/nodepools.tf

Node pool node-cycling is a feature supported only with the OKE Enhanced clusters that facilitates the replacement of nodes with a stale configuration within a node pool.
The feature is described [here](https://blogs.oracle.com/cloud-infrastructure/post/node-cycling-container-engine-kubernetes-oke) and [here](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengupgradingimageworkernode_topic-Performing_an_InPlace_Worker_Node_Update_By_Cycling_an_Existing_Node_Pool.htm).
The parameters re quired to request node_cycling on a node pool must be defined for each node_pool individually in the variable `worker_pools`:
- `node_cycling_enabled` | default value: `false`
- `node_cycling_max_surge` | default value: `1`
- `node_cycling_max_unavailable` | default value: `0`
By default, the …

Add support for node-cycling and improve control over node_pool kubernetes version

---

module-cluster.tf

Fixes evaluation of `cluster-context` local variable when cluster creation is disabled:
```
│ Error: Invalid function argument
│ 
│   on .terraform/modules/oke/module-cluster.tf line 22, in locals:
│   22:   cluster-context = "context-${substr(local.cluster_id, (length(local.cluster_id) - 11), length(local.cluster_id))}"
│     ├────────────────
│     │ while calling length(value)
│     │ local.cluster_id is null
│ 
│ Invalid value for "value" parameter: argument must not be null.
```

fix: 5.x Error handling for cluster-context w/ disabled cluster

---

examples/workers/vars-workers-node-cycling.auto.tfvars
modules/operator/compute.tf

1. Sample code on how to use nodepool node-cycling.
2. Add support to recreate the operator instance when the cloud-init provided by the user is changed.

Add example for node-cycling & improve operator life-cycle

---

module-bastion.tf
module-operator.tf
modules/operator/variables.tf
modules/workers/locals.tf
variables-cluster.tf

* Handle nulls/errors evaluating local variables for bastion, operator images (Fixes #854)
* Specify default `cluster_name` value

fix: 5.x Add null handling for bastion, operator image locals

---

docs/src/guide/topology.md

Tiny mistake in documentation of topology where in an image's caption, instead of Deploying private workers, it is incorrectly written deploying public workers.

fix tiny error in docs depicting topology

---

module-network.tf
modules/network/nsg-bastion.tf
modules/network/nsg-controlplane.tf
modules/network/nsg-fss.tf
modules/network/nsg-loadbalancers-int.tf
modules/network/nsg-loadbalancers-pub.tf
modules/network/nsg-operator.tf
modules/network/nsg-pods.tf
modules/network/nsg-workers.tf
modules/network/subnets.tf
modules/workers/instance.tf
modules/workers/instanceconfig.tf
modules/workers/locals.tf
modules/workers/variables.tf

* Latest VCN module 3.5.5
* Ignore changes non-updateable [agent_config](https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/core_instance_configuration#agent_config) on existing worker pools
* Fixes plan from full VCN recreation between versions to remaining valid diff:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "oci_core_network_security_group_security_rule" "oke" {
+ description               = "Allow TCP egress from bastion to OCI services"
+ destination               = "all-iad-services-in-oracle-services-network"
+ destination_type          = "SERVICE_CIDR_BLOCK"
+ direction                 = …
```

fix: VCN module -> 3.5.5, lifecycle ignore changed for existing resources

---

module-network.tf

This PR resolves #864 and propose to output the inner `oci-vcn` `lpg_all_attributes`.

5.x: add lpg_all_attributes output from inner vcn module

---

modules/iam/tagging.tf

There are two options to avoid an error on `terraform apply`:
1. Comment out the defined_tags attributes, as the tag namespace and the tags may not be present when we try to attach
the defined tags to the resource.
2. Apply only a set of the defined tags on initial apply (based on the existing tag namespace and tags already present) and apply the rest on the subsequent apply, but this will involve removing `defined_tags` from the ignore_changes lifecycle block and will also overwrite any defined tags added by default at the compartment level.
To avoid any error on apply, we can go with the 1st solution.
Fixes: #863

remove defined tags from iam.tagging to avoid chicken-egg problem

---

docs/src/dependencies.md
module-network.tf

This PR is bumping the internal dependency on `terraform-oci-vcn` to its latest version `v3.6.0` which [integrates the following changes](https://github.com/oracle-terraform-modules/terraform-oci-vcn/compare/v3.5.5...v3.6.0).
This also resolves issue #514.

feat: networking module - bump  to v3.6.0

---

module-operator.tf
modules/operator/cloudinit.tf
modules/operator/variables.tf
variables-operator.tf

- upgrade to operator olcne reppo to version 1.8 
- ability to install kubectl using curl from [k8s.io](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-on-linux)

Improve operator pkg installation

---

modules/network/nsg-workers.tf

Bug in NSG rule for health check? (incorrect direction, or incorrect description?)

---

examples/workers/vars-workers.auto.tfvars
modules/workers/instance.tf
modules/workers/instanceconfig.tf
modules/workers/locals.tf
variables-workers.tf

- Support `boot_volume_vpus_per_gb` in `worker_shape` and entries of `worker_pools` for self-managed modes

feat: Configurable boot volume VPUs/GB on self-managed

---

docs/src/guide/cluster.md
examples/cluster/vars-cluster-enhanced.auto.tfvars
module-cluster.tf
modules/cluster/cluster.tf
modules/cluster/variables.tf
variables-cluster.tf

Resolves[https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/869]
@Noksa / @hyder / @devoncrouse
With public subnets, we have option to either assign public IP or defer it for assignment at a later point of time. This is the feature that is being used to assign or unassign the public IP to Control plane API endpoint in OCI console. So if the cluster has been created with public subnet with/without actually assigning the public IP at the time off creation, there should be an option to toggle the public IP after cluster is provisioned.
The variable control_plane_is_public is being used in code to decide the subnet type (public or private). If we toggle this variable, the subnet recreation will kick off which will recreate the cluster and nodepools.
For solution to toggle …

Fix : Wrong control_plane_is_public behavior for OKE cluster 

---

module-iam.tf
module-network.tf
modules/iam/tagging.tf
modules/network/subnets.tf

Terraform plan and apply throw errors if a Compartment is created in the same configuration using this module and passed in through `var.compartment_id`. Same for VCNs created in the same configuration but not created by this module directly (i.e. passed in through `var.vcn_id` with `var.create_vcn = false`)
Fixes for #883

fix: Remove unknown resource counts from derived inputs

---

examples/network/vars-network.auto.tfvars
module-network.tf
modules/network/nsg-workers.tf
modules/network/variables.tf
variables-network.tf

allow user to add additional rules to the workers NSG

---

module-iam.tf
modules/workers/instanceconfig.tf
modules/workers/locals.tf

1. Add support to update cloud-init for resources using instance_config: instance_pools and clusternetworks.
2. Fix output for workers resources.
3. Fix cluster IAM prerequisite dependency.
4. Remove "oke.oraclecloud.com/tf.workspace" label from worker nodes because of inconsistent behavior.

Add several improvements and fixes

---

modules/operator/cloudinit.tf

**Problem:**
- When a custom cloud-init script with very long content is used, the operator throws a filesystem exception. This occurs because the script attempts to use the full content of the cloud-init as the filename.
**Solution:**
- Added a `try` function to catch the exception and handle it appropriately, preventing the filesystem error.
Signed-off-by: Marcelo Couto <mcouto@sossego.com.br>

fix: operator custom cloud-init error

---

examples/workers/vars-workers-instance.auto.tfvars
examples/workers/vars-workers-instancepool.auto.tfvars
modules/workers/instance.tf
modules/workers/instanceconfig.tf

Added the ability to define burstability for worker pool mode instance and instance-pool.
Fixes issue: [968](https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/968)
When worker nodes are added as instance pool or instance , we need an ability to define burstability. 
Define the worker_pools variable for oke like
```
module "k8s_infra" {
source                             = "oracle-terraform-modules/oke/oci"
version                            = "xxxx"
....
worker_pools                       = local.worker_pools
....
}
locals {
oke-vm-instance-pool-burst= {
mode             = "instance-pool",
size             = 1,
shape            = "VM.Standard.E4.Flex",
create           = true,
ocpus            = 1,
memory           = 16,
burst            = "BASELINE_1_8",   # Valid …
```

feat: Ability to define bursting for instance and instance-pool

---

examples/workers/vars-workers-instancepool.auto.tfvars
modules/workers/instanceconfig.tf

Added the ability to customize block volume creation when worker pool mode is instance-pool
Fixes issue: [969](https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/969)
Reason for this fix, if customer wants to create thousands of node added as instance-pool, it will end up creating thousands of block volume which customer may or may not need. This creates a potentially unnecessary resource cost.
When worker nodes are added as instance pool, we need an option whether to provision a block volume or not. If we choose to provision a block volume, we should be able to customize the size of the block volume.
Define the worker_pools variable for oke like
```
module "k8s_infra" {
source                             = "oracle-terraform-modules/oke/oci"
version …
```

Feat: Ability to customize block volume for instance-pool

---

docs/src/guide/cluster_addons.md
examples/cluster-addons/vars-cluster-addons.auto.tfvars
modules/cluster-addons/addons.tf

Added the ability to override existing cluster addons via an optional flag
Fixes issue [974](https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/974)

fix: Ability to override existing cluster addons

---

modules/workers/instanceconfig.tf

Resolves #980 
Fix for pod NSGs are not attached to VNICs created by the VCN-native CNI when using self-managed nodes.

Fix #980: Add pod NSG to instance configuration metadata #981

---

docs/src/guide/cluster_addons.md
examples/cluster-addons/vars-cluster-addons.auto.tfvars
modules/cluster-addons/versions.tf

Provide example about how we can use `nodeSelector` addon configuration and the `override_existing` attribute of the `oci_containerengine_addon` terraform resource, to prevent the pods associated with the essential addons from being scheduled.

Improve cluster add-ons documentation

---

module-bastion.tf
module-operator.tf
modules/bastion/cloudinit.tf
modules/bastion/variables.tf
modules/operator/cloudinit.tf
modules/operator/variables.tf
variables-bastion.tf
variables-operator.tf

- Add option to install OCI CLI and Helm from repos to support OSs like Ubuntu that does not have packages in the default repos.
- Add option to not wait for bastion and operator cloud inits (`operator_await_cloudinit` and `bastion_await_cloudinit`).
- Update `k9s` version.
- Fix a typo for `stern`.

Update operator and bastion cloud inits to support different operating systems

---

modules/cluster/cluster.tf
modules/workers/cloudinit.tf
modules/workers/locals.tf

Add support for Ubuntu images when using the `instance-pool` and `instance` mode in nodepools.
Here you can find the supported Ubuntu and Kubernetes versions:
https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingubuntubasedworkernodes.htm#contengcreatingubuntubasedworkernodes_availabilitycompatibility

Add support for Ubuntu images

---

modules/operator/cloudinit.tf

- Use the latest version of k9s
- Add a custom view to add hostname, shape, and serial
- Enable node shell

Update Operator cloud init for k9s
