oracle-terraform-modules/terraform-oci-oke

README.md
=> updated instructions

modules/base/bastion/scripts/bastion.template.sh, modules/oke/calico.tf, modules/oke/scripts/install_calico.template.sh
- update calico installation script
- removed superfluous steps in bastion hardening
=> bastion hardening improvement and calico update

README.md, docs/instructions.md, terraform.tfvars.example
- updated docs: api key gen without passphrase and README.md
- set instance_principal in terraform.tfvars.example default  to false
=> Instance principal

README.md, main.tf, modules/oke/activeworker.tf, modules/oke/variables.tf
so it is not triggered if u…ser does not have permission
=> added more checks for activeworker script

main.tf, modules/base/outputs.tf, modules/oke/activeworker.tf, modules/oke/calico.tf, modules/oke/helm.tf, modules/oke/kubeconfig.tf, modules/oke/ocir.tf, modules/oke/scripts/install_helm.template.sh, modules/oke/variables.tf, variables.tf
also added sorting on ADs in base
=> removed extra writes for tools installation

modules/oke/helm.tf
This change removes the hard dependency on Helm which was there since the tooling cleanup.
It resolves issue #18.
=> Removed hard dependency on helm

docs/terraformoptions.md, variables.tf
ocir url and documentation for seoul region
=> added values and documentation for seoul region

README.md
=> fixed broken links issue #33

.gitignore, CONTRIBUTING.md, CONTRIBUTORS.md, README.md, docs/instructions.md, docs/terraformoptions.md, main.tf, modules/auth/outputs.tf, modules/base/bastion/compute.tf, modules/base/bastion/datasources.tf, modules/base/bastion/scripts/tesseract.template.sh, modules/base/bastion/subnets.tf, modules/base/variables.tf, modules/base/vcn/vcn.tf, modules/oke/helm.tf, modules/oke/nodepools.tf, modules/oke/scripts/install_helm.template.sh, modules/oke/variables.tf, modules/okenetwork/datasources.tf, modules/okenetwork/outputs.tf, modules/okenetwork/subnets.tf, terraform.tfvars.example, variables.tf
additional check for nodepool_topology2, tesseract ssh script, incubator and jetstack helm repo options, default subnets masks for large clusters, updated terraform.tfvars.example, some instructions update
=> additional check for nodepool_topology2, tesseract script etc

modules/base/bastion/locals.tf, modules/base/bastion/security.tf, modules/base/vcn/locals.tf, modules/base/vcn/vcn.tf, modules/oke/cluster.tf, modules/oke/datasources.tf, modules/oke/locals.tf, modules/okenetwork/locals.tf, modules/okenetwork/security.tf, modules/okenetwork/subnets.tf
=> grouped all locals in a single locals.tf per module

docs/topology.adoc
=> added line break

docs/topology.adoc
=> worker node per subnet correction

docs/instructions.adoc
Instructions.adoc has been added.
=> instructions adoc

locals.tf, main.tf, modules/oke/calico.tf, modules/oke/datasources.tf, modules/oke/nodepools.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
Changes for creating different nodeshape and quantity per subnet and calico commented out.
=> Support for Mixed workloads with different nodeshape and quantity

docs/configuration.adoc, docs/instructions.adoc, docs/prerequisites.adoc, docs/terraformoptions.adoc, locals.tf, main.tf, modules/base/bastion/iam.tf, modules/base/bastion/outputs.tf, modules/base/outputs.tf, modules/kms/variables.tf, modules/oke/cluster.tf, modules/oke/outputs.tf, modules/oke/variables.tf, modules/policies/datasources.tf, modules/policies/groups.tf, modules/policies/locals.tf, modules/policies/policies.tf, modules/policies/provider.tf, modules/policies/scripts/update_dynamic_group.template.sh, modules/policies/variables.tf, variables.tf
- Added OCI KMS integration for encrypting k8s secrets
- Added outputs for instance_principal dynamic group, enabled update_dynamic_group.sh
- Updated documentation for kms
=> oci kms integration with existing key

docs/topology.adoc
=> fixed topology documentation

modules/base/admin/locals.tf, modules/base/bastion/locals.tf
=> changed uri of protocol numbers to https

CHANGELOG.adoc, main.tf, modules/auth/authtoken.tf, modules/base/admin/instance_principal.tf, modules/base/bastion/datasources.tf, modules/base/bastion/locals.tf, modules/base/bastion/ons.tf, modules/base/vcn/servicegateway.tf, modules/oke/calico.tf, modules/oke/datasources.tf, modules/oke/helm.tf, modules/oke/kubeconfig.tf, modules/oke/metricserver.tf, modules/oke/nodepools.tf, modules/oke/ocir.tf, modules/policies/groups.tf, modules/policies/policies.tf, variables.tf
=> removed quotes for references, fixed issue #103

modules/base/admin/instance_principal.tf, modules/base/admin/outputs.tf, modules/base/admin/variables.tf, modules/base/locals.tf
=> added enable_instance_principal parameter for admin module

modules/policies/locals.tf
=> fixed issue #112

docs/terraformoptions.adoc, locals.tf, main.tf, modules/oke/locals.tf, modules/oke/scripts/create_service_account.template.sh, modules/oke/serviceaccount.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
=> added scripts for serviceaccount

modules/oke/scripts/install_kubectl.template.sh
=> enabled ol7_olcne yum repo to install the latest kubectl

README.adoc, docs/dependencies.adoc, docs/terraformoptions.adoc
=> added feature dependencies documentation

CHANGELOG.adoc, docs/prerequisites.adoc, docs/quickstart.adoc, outputs.tf
=> added network outputs to facilitate reuse from hashicorp registry

modules/oke/scripts/install_metricserver.template.sh
=> updated metrics_server repo url and dependent folder

.gitignore, modules/oke/kubeconfig.tf
=> removed and tested dependency on ip.finish

README.adoc, docs/configuration.adoc, docs/dependencies.adoc, docs/instructions.adoc, docs/quickstart.adoc, docs/terraformoptions.adoc, docs/topology.adoc, docs/upgrade.adoc, locals.tf, main.tf, modules/oke/activeworker.tf, modules/oke/cluster.tf, modules/oke/datasources.tf, modules/oke/drain.tf, modules/oke/locals.tf, modules/oke/nodepools.tf, modules/oke/scripts/check_worker_active.template.sh, modules/oke/scripts/drain.template.sh, modules/oke/scripts/drainlist.py, modules/oke/variables.tf, modules/okenetwork/security.tf, modules/okenetwork/subnets.tf, modules/policies/datasources.tf, modules/policies/groups.tf, modules/policies/policies.tf, terraform.tfvars.example, variables.tf
Resolves #150 #178 #179 #181 #182 #185
=> added support for out-of-place upgrade

CHANGELOG.adoc, main.tf, modules/oke/scripts/install_kubectl.template.sh
=> updated version of base module to install kubectl

docs/configuration.adoc, docs/terraformoptions.adoc, main.tf, modules/okenetwork/security.tf, modules/okenetwork/variables.tf, terraform.tfvars.example, variables.tf
Closes #188 
Signed-off-by: Noel Dcosta <noel.dcosta@oracle.com>
=> Allow public ingress from anywhere to ports 80 and 443

docs/terraformoptions.adoc, modules/oke/datasources.tf, modules/oke/nodepools.tf, terraform.tfvars.example, variables.tf
Signed-off-by: Karthic Ravindran <karthic.ravindran@oracle.com>
In nodepool map variable an extra parameter has been added for Flex shape OCPU.
=> PR for issue-216 add support for flex shape

variables.tf
Signed-off-by: Karthic Ravindran <karthic.ravindran@oracle.com>
=> Dubai OCIR region added - Issue #220

docs/terraformoptions.adoc, main.tf, terraform.tfvars.example
so kubectl and helm can be installed
=> updated base module to temporarily disable osms 

docs/configuration.adoc, docs/instructions.adoc, docs/terraformoptions.adoc, locals.tf, main.tf, modules/oke/kubernetestools.tf, modules/oke/scripts/install_helm.template.sh, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
Kubernetes version changes in doc .Changed helm.tf to kubernetestools.tf as discussed.please review.
=> Helm install via yum

CHANGELOG.adoc, docs/terraformoptions.adoc, locals.tf, main.tf, terraform.tfvars.example, variables.tf
Also upgraded base module to v2.2.0
=> added ability to support custom route rules for NAT gateway route table

CONTRIBUTORS.adoc, README.adoc, README.md, docs/configuration.adoc, docs/dependencies.adoc, docs/instructions.adoc, docs/prerequisites.adoc, docs/quickstart.adoc, docs/terraformoptions.adoc, docs/topology.adoc, docs/upgrade.adoc
- Lesser privileges required
- Path in docs now point to main branch
=> Updated pre-requisites and path from master to main branch

docs/terraformoptions.adoc, locals.tf, main.tf, modules/oke/activeworker.tf, modules/oke/calico.tf, modules/oke/cluster.tf, modules/oke/drain.tf, modules/oke/k8stools.tf, modules/oke/kubeconfig.tf, modules/oke/locals.tf, modules/oke/metricserver.tf, modules/oke/scripts/create_service_account.template.sh, modules/oke/scripts/generate_kubeconfig.template.sh, modules/oke/scripts/install_calico.template.sh, modules/oke/scripts/install_helm.template.sh, modules/oke/scripts/install_kubectl.template.sh, modules/oke/scripts/install_metricserver.template.sh, modules/oke/secrets.tf, modules/oke/serviceaccount.tf, modules/oke/variables.tf, modules/policies/groups.tf, modules/policies/variables.tf, terraform.tfvars.example, variables.tf
Bastion state can now be controlled without destroying it
=> upgraded base module to 2.2.1. 

docs/configuration.adoc, locals.tf, modules/oke/scripts/secret.py, modules/oke/secrets.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
=> [Feature] make OCIR secret namespace configurable

modules/okenetwork/locals.tf, modules/okenetwork/security.tf, variables.tf
=> allow access to worker nodes from operator host

docs/prerequisites.adoc, variables.tf
=> added default empty string for kms_key_id

docs/quickstart.adoc, terraform.tfvars.example, variables.tf
=> updated quickstart docs so users can start testing

modules/policies/datasources.tf, modules/policies/locals.tf, modules/policies/scripts/update_dynamic_group.template.sh
for when actual region is different from home region
=> added home region to update dynamic group script 

main.tf, modules/oke/cluster.tf, modules/oke/variables.tf, modules/okenetwork/variables.tf, variables.tf
=> added support for nsgs for the cluster endpoint

modules/okenetwork/locals.tf
to allow operator to execute kubectl commands
=> fix: added 1 extra rule for control plane api 

modules/oke/scripts/generate_kubeconfig.template.sh
=> feat: always use PRIVATE_ENDPOINT from operator host

docs/configuration.adoc, docs/quickstart.adoc, docs/terraformoptions.adoc, main.tf, terraform.tfvars.example, variables.tf, versions.tf
=> changed region variable from string to map

docs/configuration.adoc, docs/quickstart.adoc, docs/terraformoptions.adoc, main.tf, terraform.tfvars.example, variables.tf
=> switch back to string value for region, added a home_region variable

main.tf
=> BREAKING CHANGE: upgraded bastion and operator modules to 3.0.0

docs/terraformoptions.adoc, modules/network/security.tf, modules/network/variables.tf, terraform.tfvars.example, variables.tf
=> feat: added support for specifying a range of allowed ports for public load balancers

THIRD_PARTY_LICENSES.txt
=> others: added 3rd party attributions

modules/extensions/calico.tf, modules/extensions/k8stools.tf, modules/extensions/kubeconfig.tf, modules/extensions/metricserver.tf, modules/extensions/serviceaccount.tf, modules/network/nsgs.tf
=> fix: added 1 additional rule to allow control plane to be accessed by specified list of cidr blocks

README.adoc, README.md, examples/verrazzano/README.md, examples/verrazzano/oke.tf, examples/verrazzano/scripts/install_verrazzano.template.sh, examples/verrazzano/scripts/install_verrazzano_operator.template.sh, examples/verrazzano/templates.tf, examples/verrazzano/terraform.tfvars.example, examples/verrazzano/v8oprovider.tf, examples/verrazzano/variables.tf, examples/verrazzano/verrazzano.tf, modules/extensions/kubeconfig.tf
Closes #435, Closes #436. 
Added example to automate Verrazzano installation.
=> fix: Created bin directory in /home/opc before moving token_helper script there.

modules/network/locals.tf
Closes #434 
Signed-off-by: Andrea Marchesini <andrea.marchesini@oracle.com>
=> fix: added 1 additional rule to allow egress traffic for load balancer health checks to work 

modules/extensions/scripts/install_kubectl.template.sh
=> feat: upgraded olcne package so we can have latest version of kubectl

main.tf, modules/extensions/templates.tf, modules/extensions/variables.tf, variables.tf
=> feat: dynamically generate the OCIR url using the region name

docs/configuration.adoc, docs/instructions.adoc, docs/terraformoptions.adoc, main.tf, modules/oke/nodepools.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
Added support for in-transit encryption in OKE and custom kms_key for boot volume encryption support
=> Added support for in-transit encryption in OKE and custom kms_key for boot volume encryption support

modules/oke/iam.tf, modules/oke/locals.tf
fix: Policies added for nodepool's boot volume and block volume encryption. Closes #460 
Signed-off-by: Srinivasa Nikhil Kota <srinivasa.nikhil.kota@oracle.com>
=> fix: Policies added for nodepool's boot volume and block volume encryption

main.tf
feat: Disable internet gateway when lbs are internal and bastion host is disabled
Signed-off-by: Nikhil Kota <srinivasa.nikhil.kota@oracle.com>
=> feat: Disable internet gateway when lbs are internal and bastion host is disabled

docs/terraformoptions.adoc, main.tf, modules/oke/cluster.tf, modules/oke/variables.tf, variables.tf
Closes #465 
Added support for adding service load balancer freeform_tags
Signed-off-by: Nikhil Kota <srinivasa.nikhil.kota@oracle.com>
=> feat: Added support for adding service loadbalancer freeform_tags

docs/configuration.adoc, docs/instructions.adoc, docs/terraformoptions.adoc, main.tf, modules/oke/iam.tf, modules/oke/locals.tf, terraform.tfvars.example, variables.tf
Added following things
1) Updated the operator to latest version
2) Added support for adding boot/block volume and in-transit encryption for Operator
Signed-off-by: Nikhil Kota <srinivasa.nikhil.kota@oracle.com>
=> feat: Added support for adding boot/block volume and in-transit encryption for Operator 

docs/dependencies.adoc
=> docs: updated dependencies chart

docs/configuration.adoc, docs/instructions.adoc, docs/terraformoptions.adoc, main.tf, modules/extensions/templates.tf, modules/extensions/variables.tf, modules/oke/cluster.tf, modules/oke/iam.tf, modules/oke/locals.tf, modules/oke/outputs.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
=> feat: renamed kms_key_id to cluster_kms_key_id to avoid confusion. 

docs/codingconventions.adoc, docs/configuration.adoc, docs/dependencies.adoc, docs/instructions.adoc, docs/terraformoptions.adoc, main.tf, modules/extensions/iam.tf, modules/extensions/locals.tf, modules/extensions/templates.tf, modules/extensions/variables.tf, modules/network/locals.tf, modules/network/nsgs.tf, modules/network/variables.tf, modules/oke/cluster.tf, modules/oke/iam.tf, modules/oke/locals.tf, modules/oke/nodepools.tf, modules/oke/outputs.tf, modules/oke/variables.tf, modules/storage/datasource.tf, modules/storage/fss.tf, modules/storage/locals.tf, modules/storage/nsg.tf, modules/storage/outputs.tf, modules/storage/subnet.tf, modules/storage/variables.tf, outputs.tf, terraform.tfvars.example, variables.tf
Closes #293. Co-authored-by: @ramesumi ramesh.rr.ramakrishnan@oracle.com
=> feat: Added fss storage module. 

modules/network/nsgs.tf
=> fix: Added additional rule to workers nsg to allow ssh

modules/extensions/calico.tf, modules/extensions/gatekeeper.tf, modules/extensions/k8stools.tf, modules/extensions/kubeconfig.tf, modules/extensions/metricserver.tf, modules/extensions/serviceaccount.tf
null resource is not needed for local kubeconfig creation since local_file resource will create it if does not exist. Merged helm install commands into kubectl null resource.
=> removed null resource for localkubeconfig and helm

versions.tf
=> changed provider to oracle/oci

.gitignore, main.tf, modules/bastionsvc/versions.tf, modules/extensions/iam.tf, modules/network/variables.tf, modules/network/versions.tf, modules/oke/iam.tf, modules/storage/fss.tf, modules/storage/versions.tf, versions.tf
=> fix: changed oci provider namespace in submodules

modules/network/locals.tf, modules/network/nsgs.tf
=> fix: added rule for internal lb. 

docs/terraformoptions.adoc, docs/upgrade.adoc, terraform.tfvars.example, variables.tf
=> feat: upgraded default Kubernetes version to v1.23.4

docs/terraformoptions.adoc, main.tf, modules/oke/cluster.tf, modules/oke/locals.tf, modules/oke/nodepools.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
=> feat: added support for OKE images for faster worker node provisioning

locals.tf, main.tf, outputs.tf, terraform.tfvars.example, variables.tf
=> feat adopt new DRG module

docs/terraformoptions.adoc, main.tf, modules/network/locals.tf, modules/network/nsgs.tf, modules/network/outputs.tf, modules/network/subnets.tf, modules/network/variables.tf, modules/oke/cluster.tf, modules/oke/nodepools.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
=> Support for VCN Native Pod Networking

modules/network/nsgs.tf, modules/network/outputs.tf, outputs.tf
=> feat: added output for all nsg ids in a map. Previous nsg outputs are deprecated

modules/extensions/scripts/install_helm.template.sh
=> fix: bug fix in helm installation script

modules/oke/cluster.tf, modules/oke/nodepools.tf, terraform.tfvars.example, variables.tf
=> feat: added freeform tagging for pvc and nodepools

locals.tf
=> fix: Support existing VCN in other compartment

modules/network/locals.tf, modules/network/nsgs.tf
Changed to reflect https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengnetworkconfig.htm#securitylistconfig:
* Moved `oci_core_network_security_group_security_rule.workers_egress_flannel` to CNI-agnostic `local.workers_egress` for node to node.
* Added `oci_core_network_security_group_security_rule.workers_ingress_npn` for pod to worker.
* Added `oci_core_network_security_group_security_rule.pods_ingress` for CP to pod, worker to pod, and pod to pod (`local.pods_ingress` existed for them but was not yet referenced).
* Added to TCP 6443/12250 to `local.pods_egress` for pod to CP.
* Updated `oci_core_network_security_group_security_rule.pods_egress_internet` from tcp to all protocols.
Signed-off-by: Devon Crouse <devon.crouse@oracle.com>
=> fix: Add missing NSG rules for VCN-Native Pod Networking

modules/network/nsgs.tf, modules/network/outputs.tf
=> fix: error referencing pod nsgs

modules/oke/nodepools.tf
=> fix: handle pod nsg id/ids issue

docs/configuration.adoc, docs/terraformoptions.adoc, main.tf, modules/oke/cluster.tf, modules/oke/nodepools.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
Closes #560 
Signed-off-by: Valentina Rossi <valentina.rossi@sighup.io>
=> feat: added tagging using defined tags #560

modules/oke/cluster.tf, modules/oke/nodepools.tf
Check for existing element in freeform and defined tags before merging
Resolves #573
Co-authored-by: Avi Miller <avi.miller@oracle.com>
Co-authored-by: Ali Mukadam <ali.mukadam@oracle.com>
Reviewed-by: Avi Miller <avi.miller@oracle.com>
=> fix: Check for existing element in freeform and defined tags 

docs/terraformoptions.adoc, modules/oke/nodepools.tf, terraform.tfvars.example
Added additional examples for other nodepool parameters
Resolves #577
=> fix: handle placement_ads for 1 AD regions.

locals.tf
ip addresses are provided
Resolves #584
=> fix: fixes condition when bastion/operator are set to false and no

modules/network/subnets.tf
Signed-off-by: Omar Aloraini <ooraini.dev@gmail.com>
Closes #589
=> network: use label_prefix in subnets dns_label

modules/oke/cluster.tf
=> fix: Ignore lifecycle changes for cluster_pod_network_options

CHANGELOG.adoc, modules/network/subnets.tf
Opening to replace https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/619 - Resolves https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/618
=> fix: Remove label_prefix from dns_label in subnets

main.tf, modules/oke/nodepools.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf
=> feat: Added support for running kube-proxy in IPVS mode

docs/terraformoptions.adoc, terraform.tfvars.example, variables.tf
=> docs: updated supported and default OKE Kubernetes versions

modules/oke/locals.tf
=> fix: Resolves #643

modules/oke/locals.tf
=> fix: made max_node_pool_size optional

modules/oke/nodepools.tf, terraform.tfvars.example
=> feat: Added support for eviction grace period.

module-operator.tf, modules/operator/cloudinit.tf, modules/operator/compute.tf, modules/operator/variables.tf, variables-operator.tf
- Incremental progress on Yum repo
- Fix operator lifecycle, image selection
- Add `install_kubectx` variable w/ default `true` for existing behavior
=> fix: Update operator cloud-init, lifecycle, image selection

modules/utilities/drain.tf
- Still pending implementation; this change fixes a variable reference issue causing errors in some cases.
=> fix: Worker drain evaluation

variables-extensions.tf, variables-utilities.tf
- Fix swapped file content/names; no functional change
=> fix: Filename fix for extensions, utilities var definitions

modules/workers/locals.tf
Minor fix for handling of worker NSG IDs between global and pool-specific values.
=> fix: Update worker NSG global/pool handling

main.tf, modules/network/locals.tf, modules/network/variables.tf
=> fix: make subnet parameters for bastion and operator optional

main.tf, modules/oke/cluster.tf, modules/oke/variables.tf, terraform.tfvars.example, variables.tf, versions.tf
- Add [oci_containerengine_cluster#type](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster#type) for [Enhanced clusters](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengworkingwithenhancedclusters.htm)
- Update `oci` provider version to `~> 4.114.0`
=> feat: Add oci_containerengine_cluster type variable

module-extensions.tf, modules/extensions/autoscaler.tf, modules/extensions/calico.tf, modules/extensions/gatekeeper.tf, modules/extensions/locals.tf, modules/extensions/metricserver.tf, modules/extensions/multus.tf, modules/extensions/prometheus.tf, modules/extensions/variables.tf, modules/extensions/versions.tf, variables-extensions.tf
- Add `state_id`, `http` provider for extensions, update locals for manifest paths
- Rename extension variables to fit convention: `..._enabled` -> `..._install`
- Add Multus extension
=> feat: 5.x Rename extension vars, provide state_id to sub-module, Multus

modules/network/locals.tf, modules/network/nsgs.tf
=> fix: separated ingress rule for operator when create_operator=false

module-bastion.tf, module-cluster.tf, module-extensions.tf, module-operator.tf, module-utilities.tf, modules/bastion/variables.tf, modules/extensions/autoscaler.tf, modules/extensions/gatekeeper.tf, modules/extensions/metricserver.tf, modules/extensions/multus.tf, modules/extensions/prometheus.tf, modules/network/subnets.tf, modules/operator/variables.tf, modules/utilities/variables.tf, modules/workers/cloudinit-oke.sh, variables-common.tf, variables-iam.tf, variables-network.tf
-     feat: Addition subnet configuration
-     fix: Cloud-init apiserver_host for self-managed
-     feat: Add direct output for apiserver_private_host
-     fix: Mark variables/locals sensitive
-     fix: Update subnets defaults to remove id, netnum
=> feat: 5.x Add name suffix to default values, misc fixes

modules/network/rules.tf
- fix: Cast NSG rule protocol for ICMP options comparison
=> fix: Cast NSG rule protocol for ICMP options comparison

module-bastion.tf, module-cluster.tf, module-iam.tf, module-network.tf, module-operator.tf, module-workers.tf, modules/cluster/cluster.tf
* Error handling for tag lookups
=> fix: 5.x Error handling for tag lookups

docs/src/guide/cluster.md, docs/src/guide/upgrade.md, docs/src/intro.md, docs/src/prerequisites.md
- Use admonitions
- Added links
- Added warnings for 5.x
=> docs: 1st doc review for 5.x

CONTRIBUTING.md
Signed-off-by: Craig Rodrigues <craig@quiknode.io>
=> fix: Update link to Oracle Contributor Agreement

modules/workers/locals.tf, modules/workers/nodepools.tf
Resolves #774 
@hyder Still needs docs/examples added per our discussion.
=> feat: 5.x Implement node_eviction_node_pool_settings

module-operator.tf
Resolves #782
Signed-off-by: Craig Rodrigues <craig@quiknode.io>
=> fix: fix ssh_to_operator output if create_bastion is false

docs/src/gs/intro.md
Added releases to main docs pages
=> docs: updated releases

module-cluster.tf, modules/network/rules.tf
=> fix: 5.x Include user-configured defined tags with cluster

modules/workers/locals.tf
=> fix defined_tags for cluster_autoscaler managed node_pools

modules/workers/locals.tf
=> fix issues with the cluster_autoscaler defined_tags for worker nodes

docs/src/guide/storage.md
Fix link to: "Provisioning PVCs on the File Storage Service"
=> fix fss link

modules/operator/cloudinit.tf
=> Update operator olcne version 1.5->1.7

modules/extensions/scripts/create_service_account.template.sh, modules/extensions/scripts/install_gatekeeper.template.sh, modules/extensions/scripts/install_metricserver.template.sh
=> exit script execution if a command fails

data-images.tf, module-cluster.tf, modules/workers/locals.tf, modules/workers/nodepools.tf
=> fix: cluster name in kubeconfig should be the same as provided

modules/network/nsg-loadbalancers-int.tf
=> fix: typo in security rule description

module-network.tf
=> fix: bug fix for custom route rules

module-extensions.tf, modules/extensions/autoscaler.tf, modules/extensions/variables.tf, modules/workers/locals.tf, modules/workers/outputs.tf
=> improve logic for the cluster autoscaler extension

module-operator.tf, modules/network/nsg-bastion.tf, modules/operator/cloudinit.tf, modules/operator/variables.tf
Updated cloud-init for operator so users can select Oracle Linux 9
=> fix: missing rule for bastion nsg to get yum updates.

module-operator.tf, modules/network/nsg-bastion.tf, modules/operator/cloudinit.tf, modules/operator/variables.tf
missing rule for bastion nsg to get yum updates.
=> fix: Updated cloud-init for operator so users can select Oracle Linux 9

docs/src/gs/intro.md
=> docs: updated docs main page

module-extensions.tf, module-operator.tf, modules/extensions/cilium.tf, modules/extensions/variables.tf, modules/operator/cloudinit.tf, modules/operator/variables.tf, variables-extensions.tf
This is a reimplementation of #722.
=> feat: added Cilium CNI.

modules/bastion/cloudinit.tf, variables-bastion.tf
=> feat: upgraded default Autonomous Linux to 8.8

module-network.tf, variables-network.tf
Add support for custom existing DRG compartment id.
=> Update drg module version. 

modules/workers/locals.tf, modules/workers/nodepools.tf
=> add nodepool support for max_pods_per_node

module-cluster.tf
=> Improve logic for kube_config datasource

module-cluster.tf, modules/extensions/rdma_cni_plugin.tf
Fix issues introduced by #909 for new clusters.
Add the changes in #873.
=> fix issue introduced by #909 with new clusters and #873

modules/network/nsg-fss.tf, modules/network/rules.tf
resolves #916 .
improves port definition for the NSG rules to resolve the FSS issue and preserves compatibility with the rule definition for the other NSGs.
=> fix FSS NSGs

module-bastion.tf, module-operator.tf, modules/bastion/cloudinit.tf, modules/bastion/variables.tf, modules/cluster/versions.tf, modules/iam/versions.tf, modules/network/versions.tf, modules/operator/versions.tf, modules/workers/versions.tf, variables-bastion.tf
additional fixes:
- for default bastion os version when using Autonomous
- disabling bastion addon when using different OS versions
- operator await should only trigger if bastion is created
Resolves #921
=> fix: versions file in submodules

module-cluster.tf, module-network.tf, modules/cluster/versions.tf, modules/extensions/autoscaler.tf, modules/iam/versions.tf, modules/network/versions.tf
=> fix symlinks issues and cluster autoscaler defaults override

modules/workers/nodepools.tf
=> Allow cloud-init update for nodepools

docs/src/guide/cluster_addons.md, docs/src/guide/extensions_networking.md, examples/extensions/vars-extensions-cilium.auto.tfvars, module-extensions.tf, module-workers.tf, modules/extensions/cilium.tf, modules/extensions/locals.tf, modules/extensions/variables.tf, modules/workers/locals.tf, variables-extensions.tf
=> Cilium extension upgrade to 1.16

modules/network/nsg-controlplane.tf
=> Fix pod nsg bug

examples/istio-mc/c1.tf, examples/istio-mc/c2.tf, examples/istio-mc/istio.tf, examples/istio-mc/locals.tf, examples/istio-mc/outputs.tf, examples/istio-mc/providers.tf, examples/istio-mc/terraform.tfvars.example, examples/istio-mc/variables.tf, module-operator.tf, modules/operator/cloudinit.tf, modules/operator/variables.tf, variables-operator.tf
=> feat: added stern, update istio-mc examples module

module-extensions.tf
fix #972 extension module fails when there is no cluster configured
=> fix #972 extension module fails when there is no cluster configured

modules/workers/clusternetworks.tf, modules/workers/instanceconfig.tf, modules/workers/instancepools.tf, modules/workers/locals.tf
=> feat: add support for using the OCI VCN-Native Pod Networking CNI plugin for pod networking with self-managed nodes

module-network.tf, modules/network/nsg-controlplane.tf, modules/network/nsg-pods.tf, modules/network/subnets.tf, modules/network/variables.tf, variables-network.tf
=> Add support to customize subnet name and extend rules for CP and Pods NSGs

modules/cluster/versions.tf, modules/workers/locals.tf
=> Fix oke image selection for A2 shapes

modules/workers/cloudinit-oke.sh
=> Improve cloud-init logic

modules/workers/cloudinit-ubuntu.sh.tftpl, modules/workers/cloudinit.tf, modules/workers/locals.tf
Improved ubuntu worker nodes bootstrapping logic.
Added loop to wait for apt lock release before attempt to install the packages.
=> Improve ubuntu worker nodes bootstrapping logic

module-workers.tf, modules/workers/computecluster.tf, modules/workers/instance.tf, modules/workers/instanceconfig.tf, modules/workers/locals.tf, modules/workers/variables.tf, variables-workers.tf
Added variable to the workers module that defaults to the existing hard coded value, in addition it is supported by each worker pool.  I also ran terraform fmt against all of the files I modified.
=> feat(workers): Add option for disabling legacy IMDS
